version: "3.9"

services:
  app:
    container_name: cooki-note-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.docker
    depends_on:
      - db
      - redis
    restart: always

  db:
    container_name: cooki-note-postgres
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p@ssword
      POSTGRES_DB: cooki-note
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    container_name: cooki-note-redis
    image: redis:7.2
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data:
