create table categories
(
    is_deleted  boolean      not null,
    category_id bigint generated by default as identity
        primary key,
    created_at  timestamp(6) not null,
    updated_at  timestamp(6) not null,
    name        varchar(100) not null
        unique,
    description varchar(500)
);

alter table categories
    owner to postgres;

create index idx_category_name
    on categories (name);

create index idx_category_created_at
    on categories (created_at);

create index idx_category_is_deleted
    on categories (is_deleted);

create table ingredients
(
    created_at    timestamp(6) not null,
    ingredient_id bigint generated by default as identity
        primary key,
    updated_at    timestamp(6) not null,
    name          varchar(100) not null
        constraint uk_ingredient_name
            unique
);

alter table ingredients
    owner to postgres;

create index idx_ingredient_name
    on ingredients (name);

create index idx_ingredient_created_at
    on ingredients (created_at);

create table media
(
    created_at timestamp(6) not null,
    media_id   bigint generated by default as identity
        primary key,
    updated_at timestamp(6) not null,
    type       varchar(20)  not null
        constraint media_type_check
            check ((type)::text = ANY
                   ((ARRAY ['IMAGE'::character varying, 'VIDEO'::character varying, 'AUDIO'::character varying])::text[])),
    url        varchar(500) not null,
    public_id  varchar(255) not null
        unique
);

alter table media
    owner to postgres;

create index idx_media_created_at
    on media (created_at);

create index idx_media_public_id
    on media (public_id);

create table users
(
    date_of_birth date,
    created_at    timestamp(6) not null,
    updated_at    timestamp(6) not null,
    user_id       bigint generated by default as identity
        primary key,
    gender        varchar(10)
        constraint users_gender_check
            check ((gender)::text = ANY
                   ((ARRAY ['MALE'::character varying, 'FEMALE'::character varying, 'OTHER'::character varying, 'UNDEFINED'::character varying])::text[])),
    role          varchar(20)  not null
        constraint users_role_check
            check ((role)::text = ANY
                   ((ARRAY ['USER'::character varying, 'ADMIN'::character varying, 'MANAGER'::character varying])::text[])),
    status        varchar(20)  not null
        constraint users_status_check
            check ((status)::text = ANY
                   ((ARRAY ['ACTIVE'::character varying, 'DEACTIVATED'::character varying, 'BANNED'::character varying])::text[])),
    first_name    varchar(50),
    last_name     varchar(50),
    provider      varchar(50),
    username      varchar(50)  not null
        unique,
    email         varchar(100) not null
        unique,
    provider_id   varchar(100),
    biography     varchar(500),
    password      varchar(255)
);

alter table users
    owner to postgres;

create table follows
(
    created_at   timestamp(6) not null,
    follower_id  bigint       not null
        constraint fk_follower_id
            references users,
    following_id bigint       not null
        constraint fk_following_id
            references users,
    constraint uk_follower_following
        primary key (follower_id, following_id)
);

alter table follows
    owner to postgres;

create index idx_follower_id
    on follows (follower_id);

create index idx_following_id
    on follows (following_id);

create table notifications
(
    is_read         boolean      not null,
    created_at      timestamp(6) not null,
    notification_id bigint generated by default as identity
        primary key,
    recipient_id    bigint       not null
        constraint fk_notification_recipient
            references users,
    sender_id       bigint
        constraint fk_notification_sender
            references users,
    target_id       bigint,
    type            varchar(30)  not null
        constraint notifications_type_check
            check ((type)::text = ANY
                   ((ARRAY ['LIKE'::character varying, 'COMMENT'::character varying, 'FOLLOW'::character varying, 'SYSTEM'::character varying])::text[])),
    message         varchar(255) not null
);

alter table notifications
    owner to postgres;

create index idx_notification_recipient
    on notifications (recipient_id);

create index idx_notification_is_read
    on notifications (is_read);

create index idx_notification_created_at
    on notifications (created_at desc);

create table recipes
(
    cook_time_minutes integer      not null,
    is_deleted        boolean      not null,
    is_public         boolean      not null,
    servings          integer      not null,
    category_id       bigint
        constraint fk_recipe_category
            references categories,
    created_at        timestamp(6) not null,
    recipe_id         bigint generated by default as identity
        primary key,
    updated_at        timestamp(6) not null,
    user_id           bigint       not null
        constraint fk_recipe_user
            references users,
    views_count       bigint       not null,
    difficulty        varchar(20)  not null
        constraint recipes_difficulty_check
            check ((difficulty)::text = ANY
                   ((ARRAY ['EASY'::character varying, 'MEDIUM'::character varying, 'HARD'::character varying, 'VERY_HARD'::character varying])::text[])),
    title             varchar(150) not null,
    description       varchar(500)
);

alter table recipes
    owner to postgres;

create table comments
(
    depth      integer      not null,
    is_deleted boolean      not null,
    comment_id bigint generated by default as identity
        primary key,
    created_at timestamp(6) not null,
    parent_id  bigint
        constraint fk_comment_parent
            references comments,
    recipe_id  bigint       not null
        constraint fk_comment_recipe
            references recipes,
    updated_at timestamp(6) not null,
    user_id    bigint       not null
        constraint fk_comment_user
            references users,
    content    text         not null
);

alter table comments
    owner to postgres;

create index idx_comment_recipe
    on comments (recipe_id);

create index idx_comment_user
    on comments (user_id);

create index idx_comment_parent
    on comments (parent_id);

create index idx_comment_recipe_created
    on comments (recipe_id, created_at);

create table meal_plans
(
    is_deleted   boolean      not null,
    meal_date    date         not null,
    created_at   timestamp(6) not null,
    meal_plan_id bigint generated by default as identity
        primary key,
    recipe_id    bigint       not null
        constraint fk_meal_plan_recipe
            references recipes,
    updated_at   timestamp(6) not null,
    user_id      bigint       not null
        constraint fk_meal_plan_user
            references users,
    meal_type    varchar(20)  not null
        constraint meal_plans_meal_type_check
            check ((meal_type)::text = ANY
                   ((ARRAY ['BREAKFAST'::character varying, 'LUNCH'::character varying, 'DINNER'::character varying, 'SNACK'::character varying])::text[])),
    note         text,
    constraint uk_meal_plan_user_date_meal_recipe
        unique (user_id, meal_date, meal_type, recipe_id)
);

alter table meal_plans
    owner to postgres;

create index idx_meal_plan_user_date
    on meal_plans (user_id, meal_date);

create index idx_meal_plan_recipe
    on meal_plans (recipe_id);

create index idx_meal_plan_user_active
    on meal_plans (user_id, is_deleted);

create table recipe_ingredients
(
    quantity      numeric(10, 2) not null,
    required      boolean        not null,
    created_at    timestamp(6)   not null,
    ingredient_id bigint         not null
        constraint fk_recipe_ingredient_ingredient
            references ingredients,
    recipe_id     bigint         not null
        constraint fk_recipe_ingredient_recipe
            references recipes,
    updated_at    timestamp(6)   not null,
    unit          varchar(50),
    note          varchar(500),
    primary key (ingredient_id, recipe_id)
);

alter table recipe_ingredients
    owner to postgres;

create index idx_recipe_ingredient_recipe
    on recipe_ingredients (recipe_id);

create index idx_recipe_ingredient_ingredient
    on recipe_ingredients (ingredient_id);

create table recipe_likes
(
    created_at timestamp(6) not null,
    recipe_id  bigint       not null
        constraint fk_like_recipe
            references recipes,
    updated_at timestamp(6) not null,
    user_id    bigint       not null
        constraint fk_like_user
            references users,
    constraint uk_user_recipe_like
        primary key (user_id, recipe_id)
);

alter table recipe_likes
    owner to postgres;

create index idx_like_recipe
    on recipe_likes (recipe_id);

create index idx_like_user
    on recipe_likes (user_id);

create index idx_like_recipe_created
    on recipe_likes (recipe_id, created_at);

create table recipe_media
(
    created_at timestamp(6) not null,
    media_id   bigint       not null
        constraint fk_recipe_media_media
            references media,
    recipe_id  bigint       not null
        constraint fk_recipe_media_recipe
            references recipes,
    updated_at timestamp(6) not null,
    type       varchar(50)  not null
        constraint recipe_media_type_check
            check ((type)::text = ANY
                   ((ARRAY ['AVATAR'::character varying, 'COVER'::character varying, 'BACKGROUND'::character varying, 'BANNER'::character varying, 'GALLERY'::character varying, 'THUMBNAIL'::character varying, 'LOGO'::character varying])::text[])),
    primary key (media_id, recipe_id)
);

alter table recipe_media
    owner to postgres;

create index idx_recipe_media_recipe_id
    on recipe_media (recipe_id);

create index idx_recipe_media_media_id
    on recipe_media (media_id);

create index idx_recipe_user
    on recipes (user_id);

create index idx_recipe_category
    on recipes (category_id);

create index idx_recipe_visibility
    on recipes (is_public);

create index idx_recipe_created_at
    on recipes (created_at);

create index idx_recipe_public_created
    on recipes (is_public, created_at);

create table shopping_lists
(
    is_deleted       boolean      not null,
    planned_date     date,
    created_at       timestamp(6) not null,
    shopping_list_id bigint generated by default as identity
        primary key,
    updated_at       timestamp(6) not null,
    user_id          bigint       not null
        constraint fk_shopping_list_user
            references users,
    status           varchar(20)  not null
        constraint shopping_lists_status_check
            check ((status)::text = ANY
                   ((ARRAY ['ACTIVE'::character varying, 'FINISHED'::character varying, 'CANCELLED'::character varying])::text[])),
    title            varchar(200) not null,
    note             varchar(500)
);

alter table shopping_lists
    owner to postgres;

create table shopping_items
(
    purchased        boolean        not null,
    quantity         numeric(38, 2) not null,
    ingredient_id    bigint         not null
        constraint fk_item_ingredient
            references ingredients,
    shopping_list_id bigint         not null
        constraint fk_item_shopping_list
            references shopping_lists,
    unit             varchar(50),
    constraint uk_item_shopping_list_ingredient
        primary key (shopping_list_id, ingredient_id)
);

alter table shopping_items
    owner to postgres;

create index idx_shopping_item_shopping_list
    on shopping_items (shopping_list_id);

create index idx_shopping_item_ingredient
    on shopping_items (ingredient_id);

create index idx_shopping_list_user
    on shopping_lists (user_id);

create index idx_shopping_list_date
    on shopping_lists (planned_date);

create index idx_shopping_list_user_status
    on shopping_lists (user_id, status);

create table steps
(
    is_deleted  boolean       not null,
    step_order  integer       not null,
    created_at  timestamp(6)  not null,
    recipe_id   bigint        not null
        constraint fk_step_recipe
            references recipes,
    step_id     bigint generated by default as identity
        primary key,
    updated_at  timestamp(6)  not null,
    description varchar(1000) not null
);

alter table steps
    owner to postgres;

create table step_media
(
    created_at timestamp(6) not null,
    media_id   bigint       not null
        constraint fk_step_media_media
            references media,
    step_id    bigint       not null
        constraint fk_step_media_step
            references steps,
    updated_at timestamp(6) not null,
    primary key (media_id, step_id)
);

alter table step_media
    owner to postgres;

create index idx_step_recipe_order
    on steps (recipe_id, step_order);

create table user_media
(
    created_at timestamp(6) not null,
    media_id   bigint       not null
        constraint fk_user_media_media
            references media,
    updated_at timestamp(6) not null,
    user_id    bigint       not null
        constraint fk_user_media_user
            references users,
    type       varchar(50)  not null
        constraint user_media_type_check
            check ((type)::text = ANY
                   ((ARRAY ['AVATAR'::character varying, 'COVER'::character varying, 'BACKGROUND'::character varying, 'BANNER'::character varying, 'GALLERY'::character varying, 'THUMBNAIL'::character varying, 'LOGO'::character varying])::text[])),
    primary key (media_id, user_id)
);

alter table user_media
    owner to postgres;

create index idx_user_email
    on users (email);

create index idx_user_username
    on users (username);

create index idx_user_status
    on users (status);

